export default [
  {
    title: 'GPS',
    icon: 'hair-cross',
    color: 'primary',
    screen: 'LogHistory',
    function: 'GPSDetection',
    permission: 'GPS',
    cta: 'View log',
  },
  {
    title: 'Accelerometer sensor',
    icon: 'compass',
    color: 'label',
    screen: 'LogHistory',
    function: 'AccelerometerSensor',
    permission: 'GPS',
    cta: 'View log'
  },
  {
    title: 'SMS',
    icon: 'message',
    color: 'warning',
    screen: 'LogHistory',
    function: 'SMSList',
    permission: 'READ_SMS',
    cta: 'View log' 
  },
  {
    title: 'Call',
    icon: 'phone',
    color: 'info',
    screen: 'LogHistory',
    function: 'CallLog',
    permission: 'READ_CALL_LOG',
    cta: 'View log' 
  },
  {
    title: 'App Usage',
    icon: 'database',
    color: 'error',
    screen: 'LogHistory',
    function: 'AppUsage',
    permission: 'APP_USAGE',
    cta: 'View log', 
  },
  {
    title: 'Web Browser',
    icon: 'browser',
    color: 'facebook',
    screen: 'LogHistory',
    function: 'WebHistory',
    permission: 'WEB_HISTORY',
    cta: 'View log', 
  },
  {
    title: 'Battery Status',
    icon: 'battery',
    color: 'success',
    screen: 'BatteryStatus',
    permission: 'BATTERY',
    cta: 'View log', 
  },
  {
    title: 'Key stroke speed tracking',
    icon: 'keyboard',
    color: 'twitter',
    screen: 'KeyboardTracking',
    permission: 'KEYBOARD',
    cta: 'View log', 
  },
];